name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build for linux/am64
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
        
    - name: Install dependencies
      run: go mod download
        
    - name: Build binaries
    # exclude tests dir for now as it doesnt work well with GH actions
      run: |
        go build -o bin/logdy 
    
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: logdy
        path: bin/logdy
