name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
        
    - name: Install dependencies
      run: go mod download
        
    - name: Run tests
    # exclude tests dir for now as it doesnt work well with GH actions
      run: go test -v `go list ./... | grep -v tests`
